### ISSUE TITLE
need authority to download the pretrain model

### ISSUE THREAD

**Issue by JusticeLin** [aiff22/PyNET-Bokeh#15]
When I want to download the pretrain model from Google Drive,it declares that I need some authority to access.And I apply for it，but one day later，I can not access the link，either.Could you please check if the link was set by you or not when someone need to download the model.Thank you  very much!

**Comment by mkuzyshynAS** [comment]
+1 to this issue

**Comment by pedroHuang123** [comment]
+1 too, please share the pre-trained model

**Comment by aiff22** [comment]
An updated link to pre-trained PyNet model was added.
