### ISSUE TITLE
How to convert PyNET to TFlite

### ISSUE THREAD

**Issue by xueqinChen** [aiff22/PyNET-Bokeh#3]
Hi，
I Want to  run this model on my android phone.

I convert it to frozen graph，and use follow code to convert to tflite.
`converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph('./models/pb/output_graph.pb',
     input_arrays=["Placeholder"], 
     output_arrays=['save/restore_all'],
     input_shapes={"Placeholder":[1,768,512,4]})`

But  a error occured ：`ValueError: Input 0 of node save/AssignVariableOp was passed float from generator/Variable:0 incompatible with expected resource.`

Could you give me a hand.

**Comment by aiff22** [comment]
Hi @xueqinChen,

Please refer to [this script](https://github.com/aiff22/ai-challenge/blob/master/convert_to_tflite.py) showing how to convert your model directly from a TF session.

**Comment by xueqinChen** [comment]
Thank you！

**Comment by make-j64** [comment]
@xueqinChen did you convert this model to TFlite successfull?

**Comment by aiff22** [comment]
There should be no more problems with converting this model to TFLite when using the latest TF builds (2.5+).
