### ISSUE TITLE
getting started with ebb dataset

### ISSUE THREAD

**Issue by bbowles-personal** [aiff22/PyNET-Bokeh#5]
Can you please provide a few more details on how to download the EBB dataset and arrange the files properly? It looks like certain parts of the EBB dataset are currently with held on the website, so its not totally clear what parts are required to actually train the model.
if its possible to download a fully trained PyNet-Bokeh model, that would also be super helpful.

**Comment by aiff22** [comment]
> Can you please provide a few more details on how to download the EBB dataset and arrange the files properly?

You can access the training part of the EBB! dataset after registering in the [previous AIM 2020 Challenge](https://competitions.codalab.org/competitions/24716).
