### ISSUE TITLE
How to convert to TFLite w/o Instance Norm?

### ISSUE THREAD

**Issue by make-j64** [aiff22/PyNET-Bokeh#6]
Dear @aiff22,
Im trying to convert the checkpoint to TFlite format w/o Instance Norm like 4.4 Section in paper, but not successful.

**Comment by aiff22** [comment]
You need to remove instance norm ops completely from the model and then fine-tune it for several epochs. However, this op is already supported by latest TFLite GPU delegate, therefore there is no longer need for this.
