### ISSUE TITLE
EBB dataset

### ISSUE THREAD

**Issue by nuvinga** [aiff22/PyNET-Bokeh#7]
Hi, Where can I find the EBB complete dataset?

The competition site, to which I'm directed to get the test dataset at-leats to is not updated since 2020. So it does not provide the complete dataset.

This is for a university project. Would be appreciated very much if this could be addressed ASAP.

**Comment by aiff22** [comment]
> Hi, Where can I find the EBB complete dataset?

You can download the entire training part of the dataset after registering in the competition.

**Comment by SueeH** [comment]
> 
![image](https://user-images.githubusercontent.com/28698695/163787792-f6021219-c636-47f9-85fb-d645513831b9.png)
Hi I find train dataset(with & without bokeh), but no bokeh image of valid or test sets, could you share the 200 valid bokeh
image? Thanks a lot.

**Comment by shankerabhigyan** [comment]
Could you kindly share the same with me, also what images are supposed to be in the original_depth folder?

**Comment by CaptainEven** [comment]
I can not find any dataset link now!

**Comment by Double2016** [comment]
How to get this?I didn't get any reply  after registering in the competition. @SueeH

**Comment by ai2ys** [comment]
Is the dataset still available? 
I could not find it after registering?

**Comment by aiff22** [comment]
Please check the updated links in this repo.
